quarkus.datasource.db-kind=postgresql
quarkus.datasource.username=admin
quarkus.datasource.password=root
quarkus.datasource.jdbc.url=jdbc:postgresql://localhost:5432/challange

quarkus.hibernate-orm.database.generation=update